#!/bin/bash
# configure-efm.sh - Configure EFM for this node
#
# This script generates the EFM configuration based on environment variables.

set -e

# Configuration from environment
NODE_ROLE="${NODE_ROLE:-primary}"
EFM_CLUSTER_NAME="${EFM_CLUSTER_NAME:-efm}"
EFM_DB_PASSWORD="${EFM_DB_PASSWORD:-efm_pass}"
PRIMARY_HOST="${PRIMARY_HOST:-}"
STANDBY_HOSTS="${STANDBY_HOSTS:-}"
THIS_NODE_IP="${THIS_NODE_IP:-}"
EFM_BIND_ADDRESS="${EFM_BIND_ADDRESS:-}"

# Get this node's IP if not set
if [ -z "$THIS_NODE_IP" ]; then
    THIS_NODE_IP=$(hostname -I | awk '{print $1}')
fi

if [ -z "$EFM_BIND_ADDRESS" ]; then
    EFM_BIND_ADDRESS="$THIS_NODE_IP"
fi

echo "Configuring EFM..."
echo "  Node Role: ${NODE_ROLE}"
echo "  Node IP: ${THIS_NODE_IP}"
echo "  Bind Address: ${EFM_BIND_ADDRESS}"
echo "  Cluster Name: ${EFM_CLUSTER_NAME}"

# Encrypt the database password
EFM_BIN="/usr/edb/efm-${EFM_VERSION}/bin"
export EFMPASS="${EFM_DB_PASSWORD}"
ENCRYPTED_PASSWORD=$("${EFM_BIN}/efm" encrypt "${EFM_CLUSTER_NAME}" --from-env 2>/dev/null || echo "")
if [ -z "$ENCRYPTED_PASSWORD" ]; then
    echo "Warning: Could not encrypt password, using plaintext (not recommended for production)"
    ENCRYPTED_PASSWORD="${EFM_DB_PASSWORD}"
fi

# Create EFM properties file with all required properties
cat > "/etc/edb/efm-${EFM_VERSION}/efm.properties" << EOF
# EFM Cluster Configuration
# Generated by configure-efm.sh

# Cluster identification
cluster.name=${EFM_CLUSTER_NAME}

# Database connection
db.user=efm
db.password.encrypted=${ENCRYPTED_PASSWORD}
db.port=5432
db.database=postgres
db.service.owner=postgres
db.service.name=
db.bin=/usr/lib/postgresql/${PG_MAJOR}/bin
db.data.dir=/var/lib/postgresql/data
db.config.dir=

# Database connection settings
db.reuse.connection.count=0

# SSL settings
jdbc.sslmode=disable

# Network binding
bind.address=${EFM_BIND_ADDRESS}:7800
external.address=
admin.port=7809

# Node type
is.witness=false

# Auto configuration
auto.allow.hosts=true
stable.nodes.file=false

# Timeouts
local.period=10
local.timeout=60
local.timeout.final=10
remote.timeout=10
node.timeout=50

# Failover settings
auto.failover=true
auto.reconfigure=true
promotable=true
minimum.standbys=0
recovery.check.period=5
restart.connection.timeout=60
auto.resume.period=0

# Encryption
encrypt.agent.messages=false

# Primary isolation handling
stop.isolated.primary=true
stop.failed.primary=true
primary.shutdown.as.failure=false

# Replication
db.replication.timeout=30
update.physical.slots.period=0
standby.restart.delay=0
use.replay.tiebreaker=true
reconfigure.num.sync=0
reconfigure.sync.primary=false

# Virtual IP settings
virtual.ip=
virtual.ip.interface=
virtual.ip.prefix=
virtual.ip.single=true
check.vip.before.promotion=false

# Notifications - use a dummy email for testing
user.email=efm@localhost
from.email=efm@localhost
notification.level=INFO
notification.text.prefix=
script.notification=

# Scripts (optional)
script.fence=
script.post.promotion=
script.resumed=
script.db.failure=
script.primary.isolated=
script.remote.pre.promotion=
script.remote.post.promotion=
script.custom.monitor=
custom.monitor.interval=
custom.monitor.timeout=
custom.monitor.safe.mode=

# Load balancer scripts
script.load.balancer.attach=
script.load.balancer.detach=
detach.on.agent.failure=true

# Pgpool settings
pgpool.enable=false
pcp.user=
pcp.host=
pcp.port=
pcp.pass.file=
pgpool.bin=

# Sudo commands
sudo.command=sudo
sudo.user.command=sudo -u %u

# Directories
lock.dir=/var/lock/efm-${EFM_VERSION}
pid.dir=/var/run/efm-${EFM_VERSION}
log.dir=/var/log/efm-${EFM_VERSION}

# Syslog
syslog.host=localhost
syslog.port=514
syslog.protocol=UDP
syslog.facility=LOCAL1

# Logging
file.log.enabled=true
syslog.enabled=false
jgroups.loglevel=INFO
efm.loglevel=INFO

# JVM options
jvm.options=-Xmx128m

# Ping server for network health check
ping.server.ip=8.8.8.8
ping.server.command=/bin/ping -q -c3 -w5

# Application name for replication
application.name=efm_$(hostname | tr '-' '_')
EOF

# Set proper permissions - must be readable by postgres for efm_db_functions
chown efm:efm "/etc/edb/efm-${EFM_VERSION}/efm.properties"
chmod 640 "/etc/edb/efm-${EFM_VERSION}/efm.properties"
# Add postgres to efm group if not already
usermod -aG efm postgres 2>/dev/null || true

# Create nodes file with known cluster members
NODES_FILE="/etc/edb/efm-${EFM_VERSION}/efm.nodes"
echo "# EFM cluster nodes" > "$NODES_FILE"

# Add this node
echo "${THIS_NODE_IP}:7800" >> "$NODES_FILE"

# Add primary if we're a standby
if [ "$NODE_ROLE" = "standby" ] && [ -n "$PRIMARY_HOST" ]; then
    # Resolve primary hostname to IP
    PRIMARY_IP=$(getent hosts "$PRIMARY_HOST" | awk '{print $1}' | head -1)
    if [ -n "$PRIMARY_IP" ] && [ "$PRIMARY_IP" != "$THIS_NODE_IP" ]; then
        echo "${PRIMARY_IP}:7800" >> "$NODES_FILE"
    fi
fi

# Add any additional standby hosts
if [ -n "$STANDBY_HOSTS" ]; then
    for host in $(echo "$STANDBY_HOSTS" | tr ',' ' '); do
        HOST_IP=$(getent hosts "$host" | awk '{print $1}' | head -1)
        if [ -n "$HOST_IP" ] && [ "$HOST_IP" != "$THIS_NODE_IP" ]; then
            echo "${HOST_IP}:7800" >> "$NODES_FILE"
        fi
    done
fi

chown efm:efm "$NODES_FILE"
chmod 644 "$NODES_FILE"

echo "EFM configuration complete"
echo "Properties file: /etc/edb/efm-${EFM_VERSION}/efm.properties"
echo "Nodes file content:"
cat "$NODES_FILE"
